name: UI Tests

on: pull_request

jobs:
  Tests:
    runs-on: ubuntu-latest
    env:
      SUMMARY: |
        Hi @${{ github.event.pull_request.user.login }}! ðŸ‘‹

        It looks like you've opened a [PR#${{github.event.pull_request.number}}](https://github.com/quasarframework/quasar/pull/${{github.event.pull_request.number}}).
        We've detected file changes inside the UI folder, so that triggered our Cypress component tests. Results could be seen below.

        Thank you for your contribution. ðŸ‘

    name: 'UI tests'
    steps:

      - name: Adding markdown
        run: echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

